arr = input().split()
a = arr.copy()
a[0] = a[0].replace('6','5')
a[1] = a[1].replace('6','5')
b = arr.copy()
b[0] = b[0].replace('5','6')
b[1] = b[1].replace('5','6')
a = list(map(int, a))
b = list(map(int, b))
print(sum(a) if sum(a) <= sum(b) else sum(b), sum(b) if sum(b) >= sum(b) else sum(a))
